services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: filekeep-client
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    ports:
      - "5173:5173"
volumes:
  node_modules:
